# Generated by Django 5.2.5 on 2025-11-21 13:57

import users.models.validators_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='foto_perfil',
            field=models.ImageField(upload_to='fotos_perfil/', validators=[users.models.validators_models.validate_image_or_pdf, users.models.validators_models.validate_file_size]),
        ),
    ]
