# Generated by Django 5.2.4 on 2025-11-25 05:59

import users.models.validators_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_studentprofile_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='senha_custom',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to='curriculos/', validators=[users.models.validators_models.validate_image_or_pdf, users.models.validators_models.validate_file_size]),
        ),
    ]
