# Generated by Django 5.2.5 on 2025-11-25 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_senha_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='crp_supervisor',
            field=models.CharField(blank=True, help_text='CRP do seu supervisor psicológico', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='comprovante_matricula',
            field=models.FileField(upload_to='comprovantes/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='documento_oficial',
            field=models.FileField(upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='foto_perfil',
            field=models.ImageField(upload_to='students/fotos/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='nome_completo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
